"""add weekly schedule

Revision ID: 1c78ceb8f4f4
Revises: 760a9709429f
Create Date: 2026-09-27 21:59:10.252583

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c78ceb8f4f4"
down_revision: str | Sequence[str] | None = "760a9709429f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schedule_intervals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("host_id", sa.Integer(), nullable=False),
        sa.Column("weekday", sa.SmallInteger(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.CheckConstraint("end_time > start_time", name="end_after_start"),
        sa.CheckConstraint("weekday BETWEEN 0 AND 6", name="weekday_valid"),
        sa.ForeignKeyConstraint(["host_id"], ["hosts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_schedule_intervals_host_id"), "schedule_intervals", ["host_id"], unique=False
    )
    # ### end Alembic commands ###
    # Hosts who signed up before Weekly Schedules existed get the default one:
    # Monday to Friday, 09:00-17:00.
    op.execute(
        """
        INSERT INTO schedule_intervals (host_id, weekday, start_time, end_time)
        SELECT hosts.id, weekday, TIME '09:00', TIME '17:00'
        FROM hosts CROSS JOIN generate_series(0, 4) AS weekday
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_schedule_intervals_host_id"), table_name="schedule_intervals")
    op.drop_table("schedule_intervals")
    # ### end Alembic commands ###
