"""add bookings

Revision ID: 70b9a83ccf2e
Revises: 1c78ceb8f4f4
Create Date: 2026-09-27 22:03:30.873136

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "70b9a83ccf2e"
down_revision: str | Sequence[str] | None = "1c78ceb8f4f4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # The no-overlap exclusion constraint compares host_id with `=` in a GiST index,
    # which needs btree_gist. Left installed on downgrade: it's harmless and shared.
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bookings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("host_id", sa.Integer(), nullable=False),
        sa.Column("event_type_id", sa.Integer(), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("guest_name", sa.String(length=100), nullable=False),
        sa.Column("guest_email", sa.String(length=320), nullable=False),
        sa.Column("guest_note", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        postgresql.ExcludeConstraint(
            (sa.column("host_id"), "="),
            (sa.text("tstzrange(start_at, end_at, '[)')"), "&&"),
            where=sa.text("status = 'active'"),
            using="gist",
            name="bookings_no_overlap",
        ),
        sa.CheckConstraint("status IN ('active', 'cancelled')", name="status_valid"),
        sa.CheckConstraint("end_at > start_at", name="end_after_start"),
        sa.ForeignKeyConstraint(["event_type_id"], ["event_types.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["host_id"], ["hosts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bookings_host_id"), "bookings", ["host_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bookings_host_id"), table_name="bookings")
    op.drop_table("bookings")
    # ### end Alembic commands ###
